#include "Utility.h"
#include <vector>

class DetectionManager {
    double average;
    int averageAmount;
    
    std::vector<Minion*>  *allyMinions;
    std::vector<Minion*> *enemyMinions;
    std::vector<Champion*> *allyChampions;
    std::vector<Champion*> *enemyChampions;
    std::vector<Champion*> *selfChampions;
    std::vector<Tower*> *enemyTowers;
    bool spell1LevelUpAvailable = false, spell2LevelUpAvailable = false, spell3LevelUpAvailable = false, spell4LevelUpAvailable = false;
    GenericObject* spell1LevelUp=NULL, *spell2LevelUp=NULL, *spell3LevelUp=NULL, *spell4LevelUp=NULL;
    std::vector<GenericObject*> *spell1LevelDots, *spell2LevelDots, *spell3LevelDots, *spell4LevelDots;
    bool spell1LevelDotsVisible = false, spell2LevelDotsVisible = false, spell3LevelDotsVisible = false, spell4LevelDotsVisible = false;
    int currentLevel = 0;
    bool spell1ActiveAvailable = false, spell2ActiveAvailable = false, spell3ActiveAvailable = false, spell4ActiveAvailable = false;
    GenericObject* spell1Active=NULL, *spell2Active=NULL, *spell3Active=NULL, *spell4Active=NULL;
    bool summonerSpell1ActiveAvailable = false, summonerSpell2ActiveAvailable = false;
    GenericObject* summonerSpell1Active=NULL, *summonerSpell2Active=NULL;
    bool trinketActiveAvailable = false;
    GenericObject* trinketActive=NULL;
    bool item1ActiveAvailable = false, item2ActiveAvailable = false, item3ActiveAvailable = false, item4ActiveAvailable = false, item5ActiveAvailable = false, item6ActiveAvailable = false;
    GenericObject* item1Active=NULL, *item2Active=NULL, *item3Active=NULL, *item4Active=NULL, *item5Active=NULL, *item6Active=NULL;
    bool potionActiveAvailable = false;
    int potionOnActive;
    GenericObject* potionActive=NULL;
    bool potionBeingUsedShown = false;
    GenericObject* potionBeingUsed=NULL;
    bool shopAvailableShown = false;
    GenericObject* shopAvailable=NULL;
    bool shopTopLeftCornerShown = false;
    GenericObject* shopTopLeftCorner=NULL;
    bool shopBottomLeftCornerShown = false;
    GenericObject* shopBottomLeftCorner=NULL;
    std::vector<GenericObject*> *buyableItems;
    bool mapVisible = false;
    GenericObject* map=NULL;
    bool mapShopVisible = false;
    GenericObject* mapShop=NULL;
    bool mapSelfLocationVisible = false;
    GenericObject* mapSelfLocation=NULL;
    bool selfHealthBarVisible = false;
    SelfHealth* selfHealthBar=NULL;
    bool surrenderAvailable = false;
    GenericObject* surrenderActive = NULL;
    
public:
    DetectionManager();
    void processDetection(ImageData *image);


    void processAllyMinionDetection(ImageData *image, int x, int y, uint8_t* pixel);
    void processEnemyMinionDetection(ImageData *image, int x, int y, uint8_t* pixel);
    void processAllyChampionDetection(ImageData *image, int x, int y, uint8_t* pixel);
    void processEnemyChampionDetection(ImageData *image, int x, int y, uint8_t* pixel);
    void processEnemyTowerDetection(ImageData *image, int x, int y, uint8_t* pixel);
    void processSelfChampionDetection(ImageData *image, int x, int y, uint8_t* pixel);
    void processShop(ImageData *image, int x, int y, uint8_t* pixel);

    void processSelfHealthBarDetection(ImageData *image);
    void processSpellLevelUps(ImageData *image);
    void processSpellLevelDots(ImageData *image);
    void processSpellActives(ImageData *image);
    void processSummonerSpellActives(ImageData *image);
    void processTrinketActive(ImageData *image);
    void processSurrender(ImageData *image);
    void processItemActives(ImageData *image);
    void processUsedPotion(ImageData *image);
    void processShopAvailable(ImageData *image);
    void processShopBottomLeftCorner(ImageData *image);
    void processShopBuyableItems(ImageData *image);
    void processMap(ImageData *image);
    void processMapShopAndLocation(ImageData *image);
    
    std::vector<Minion*>* getAllyMinions();
    std::vector<Minion*>* getEnemyMinions();
    std::vector<Champion*>* getAllyChampions();
    std::vector<Champion*>* getEnemyChampions();
    std::vector<Tower*>* getEnemyTowers();
    std::vector<Champion*>* getSelfChampions();
    bool getSelfHealthBarVisible();
    SelfHealth* getSelfHealthBar();
    bool getSpell1LevelUpVisible();
    bool getSpell2LevelUpVisible();
    bool getSpell3LevelUpVisible();
    bool getSpell4LevelUpVisible();
    GenericObject* getSpell1LevelUp();
    GenericObject* getSpell2LevelUp();
    GenericObject* getSpell3LevelUp();
    GenericObject* getSpell4LevelUp();
    std::vector<GenericObject*>* getSpell1LevelDots();
    std::vector<GenericObject*>* getSpell2LevelDots();
    std::vector<GenericObject*>* getSpell3LevelDots();
    std::vector<GenericObject*>* getSpell4LevelDots();
    int getCurrentLevel();
    bool getSpell1Available();
    bool getSpell2Available();
    bool getSpell3Available();
    bool getSpell4Available();
    GenericObject* getSpell1();
    GenericObject* getSpell2();
    GenericObject* getSpell3();
    GenericObject* getSpell4();
    bool getSummonerSpell1Available();
    bool getSummonerSpell2Available();
    GenericObject* getSummonerSpell1();
    GenericObject* getSummonerSpell2();
    bool getTrinketActiveAvailable();
    GenericObject* getTrinketActive();
    bool getItem1ActiveAvailable();
    bool getItem2ActiveAvailable();
    bool getItem3ActiveAvailable();
    bool getItem4ActiveAvailable();
    bool getItem5ActiveAvailable();
    bool getItem6ActiveAvailable();
    GenericObject* getItem1Active();
    GenericObject* getItem2Active();
    GenericObject* getItem3Active();
    GenericObject* getItem4Active();
    GenericObject* getItem5Active();
    GenericObject* getItem6Active();
    bool getPotionActiveAvailable();
    GenericObject* getPotionActive();
    bool getPotionBeingUsedVisible();
    GenericObject* getPotionBeingUsed();
    bool getShopAvailable();
    GenericObject* getShopAvailableObject();
    bool getShopTopLeftCornerVisible();
    GenericObject* getShopTopLeftCorner();
    bool getShopBottomLeftCornerVisible();
    GenericObject* getShopBottomleftCorner();
    std::vector<GenericObject*>* getBuyableItems();
    bool getMapVisible();
    GenericObject* getMap();
    bool getMapShopVisible();
    GenericObject* getMapShop();
    bool getMapLocationVisible();
    GenericObject* getMapLocation();
    bool getSurrenderAvailable();
    GenericObject* getSurrender();
    int getPotionActiveItemSlot();
};